# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(username: "James", password: "jamesjames")

Notebook.create(title: "The American West", description: '{"ops":[{"insert":"States in the American West."}]}', author_id: 1)

wyoming_body = "{\"ops\":[{\"attributes\":{\"link\":\"http://www.wyomingtourism.org/\",\"bold\":true,\"color\":\"rgb(37, 37, 37)\"},\"insert\":\"Wyoming\"},{\"insert\":\" is a state in the \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"link\":\"https://en.wikivoyage.org/wiki/Rocky_Mountains_(United_States_of_America)\"},\"insert\":\"Rocky Mountain\"},{\"insert\":\" region of the \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"link\":\"https://en.wikivoyage.org/wiki/United_States_of_America\"},\"insert\":\"United States of America\"},{\"insert\":\".\\n\\nWyoming is a great place to discover the American West. With many unspoiled mountain vistas, vast blue skies and the awe-inspiring scenery of the high plains and Rocky Mountains, Wyoming offers much of what travelers to this region seek. Unlike other states in the Rockies, Wyoming's demographic growth has been restricted to a few areas of the state where mineral extraction has expanded in the recent past. While mining and drilling have expanded recently (and very notably in some regions), Wyoming is still relatively unspoiled compared to other parts of the region.\\n\\n\"},{\"attributes\":{\"image\":\"http://www.travisnovitsky.com/Beyond-Minnesota/Wyoming/i-w4t934b/0/XL/WYOMING%207388-XL.jpg\"},\"insert\":1},{\"insert\":\"\\n\"}]}"
Note.create(title: "Wyoming", body: wyoming_body, author_id: 1, notebook_id: 1)

nevada_body = "{\"ops\":[{\"attributes\":{\"bold\":true},\"insert\":\"Nevada\"},{\"insert\":\" is an arid state of the \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"link\":\"https://en.wikivoyage.org/wiki/USA\"},\"insert\":\"USA\"},{\"insert\":\", lying between \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"link\":\"https://en.wikivoyage.org/wiki/California\"},\"insert\":\"California\"},{\"insert\":\" and \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"link\":\"https://en.wikivoyage.org/wiki/Utah\"},\"insert\":\"Utah\"},{\"insert\":\". Most of the state is within the \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"link\":\"https://en.wikivoyage.org/wiki/Great_Basin\"},\"insert\":\"Great Basin\"},{\"insert\":\", but parts of the northeast drain into the Snake River and the southern portion is within the Mohave desert and the Colorado river drainage. Please note that while many outsiders pronounce the state's name as \\\"ne-VAH-duh\\\", the correct local pronunciation is [nəˈvædə], with a short \\\"a\\\" as in \\\"apple.\\\"\\n\\n\"},{\"attributes\":{\"image\":\"https://c1.staticflickr.com/9/8071/8314471603_0bcd431766_b.jpg\"},\"insert\":1},{\"insert\":\"\\n\"}]}"
Note.create(title: "Nevada", body: nevada_body, author_id: 1, notebook_id: 1)

colorado_body = "{\"ops\":[{\"attributes\":{\"link\":\"http://www.colorado.com/\",\"bold\":true,\"color\":\"rgb(37, 37, 37)\"},\"insert\":\"Colorado\"},{\"insert\":\" is a state of wild contrasts. From the flat plains of the eastern portion of the state to some of the \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"link\":\"https://en.wikivoyage.org/wiki/Rocky_Mountains_(United_States_of_America)\"},\"insert\":\"Rocky Mountains\"},{\"insert\":\"' highest peaks to the high desert and red rock country of the western reaches of the state, the landscape is incredibly varied, home to many diverse ecosystems and natural marvels, and supports a thriving hunting and outdoors culture that draws people from around the world.\\n\\n\"},{\"attributes\":{\"image\":\"http://www.1zoom.net/big2/913/256951-svetik.jpg\"},\"insert\":1},{\"insert\":\"\\n\"}]}"
Note.create(title: "Colorado", body: colorado_body, author_id: 1, notebook_id: 1)

utah_body = "{\"ops\":[{\"attributes\":{\"bold\":true,\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\",\"link\":\"http://www.utah.com/\"},\"insert\":\"Utah\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\", located in the \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\",\"link\":\"https://en.wikivoyage.org/wiki/Southwest_(United_States_of_America)\"},\"insert\":\"Southwest\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\" region of the \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\",\"link\":\"https://en.wikivoyage.org/wiki/United_States\"},\"insert\":\"United States\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\", is well known for its incredible scenic beauty and year round outdoor activities including skiing, snowboarding, hiking, boating, water skiing, horseback riding, camping, and rock climbing. The capital city of \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\",\"link\":\"https://en.wikivoyage.org/wiki/Salt_Lake_City\"},\"insert\":\"Salt Lake City\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\" has a number of unique modern and historical sites to visit, including Temple Square, the headquarters for the Mormon church.\"},{\"insert\":\"\\n\\n\"},{\"attributes\":{\"image\":\"http://www.jimshoemakerphotography.com/data/photos/12_1arches50.jpg\"},\"insert\":1},{\"insert\":\"\\n\"}]}"
Note.create(title: "Nevada", body: utah_body, author_id: 1, notebook_id: 1)
