# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(username: "guest", password: "password")

Notebook.create(title: "The West", description: '{"ops":[{"insert":"States in the American West."}]}', author_id: 1)

wyoming_body = "{\"ops\":[{\"attributes\":{\"link\":\"http://www.wyomingtourism.org/\",\"bold\":true,\"color\":\"rgb(37, 37, 37)\"},\"insert\":\"Wyoming\"},{\"insert\":\" is a state in the \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"link\":\"https://en.wikivoyage.org/wiki/Rocky_Mountains_(United_States_of_America)\"},\"insert\":\"Rocky Mountain\"},{\"insert\":\" region of the \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"link\":\"https://en.wikivoyage.org/wiki/United_States_of_America\"},\"insert\":\"United States of America\"},{\"insert\":\".\\n\\nWyoming is a great place to discover the American West. With many unspoiled mountain vistas, vast blue skies and the awe-inspiring scenery of the high plains and Rocky Mountains, Wyoming offers much of what travelers to this region seek. Unlike other states in the Rockies, Wyoming's demographic growth has been restricted to a few areas of the state where mineral extraction has expanded in the recent past. While mining and drilling have expanded recently (and very notably in some regions), Wyoming is still relatively unspoiled compared to other parts of the region.\\n\\n\"},{\"attributes\":{\"image\":\"http://www.travisnovitsky.com/Beyond-Minnesota/Wyoming/i-w4t934b/0/XL/WYOMING%207388-XL.jpg\"},\"insert\":1},{\"insert\":\"\\n\"}]}"
Note.create(title: "Wyoming", body: wyoming_body, author_id: 1, notebook_id: 1)

nevada_body = "{\"ops\":[{\"attributes\":{\"bold\":true},\"insert\":\"Nevada\"},{\"insert\":\" is an arid state of the \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"link\":\"https://en.wikivoyage.org/wiki/USA\"},\"insert\":\"USA\"},{\"insert\":\", lying between \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"link\":\"https://en.wikivoyage.org/wiki/California\"},\"insert\":\"California\"},{\"insert\":\" and \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"link\":\"https://en.wikivoyage.org/wiki/Utah\"},\"insert\":\"Utah\"},{\"insert\":\". Most of the state is within the \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"link\":\"https://en.wikivoyage.org/wiki/Great_Basin\"},\"insert\":\"Great Basin\"},{\"insert\":\", but parts of the northeast drain into the Snake River and the southern portion is within the Mohave desert and the Colorado river drainage. Please note that while many outsiders pronounce the state's name as \\\"ne-VAH-duh\\\", the correct local pronunciation is [nəˈvædə], with a short \\\"a\\\" as in \\\"apple.\\\"\\n\\n\"},{\"attributes\":{\"image\":\"https://c1.staticflickr.com/9/8071/8314471603_0bcd431766_b.jpg\"},\"insert\":1},{\"insert\":\"\\n\"}]}"
Note.create(title: "Nevada", body: nevada_body, author_id: 1, notebook_id: 1)

colorado_body = "{\"ops\":[{\"attributes\":{\"link\":\"http://www.colorado.com/\",\"bold\":true,\"color\":\"rgb(37, 37, 37)\"},\"insert\":\"Colorado\"},{\"insert\":\" is a state of wild contrasts. From the flat plains of the eastern portion of the state to some of the \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"link\":\"https://en.wikivoyage.org/wiki/Rocky_Mountains_(United_States_of_America)\"},\"insert\":\"Rocky Mountains\"},{\"insert\":\"' highest peaks to the high desert and red rock country of the western reaches of the state, the landscape is incredibly varied, home to many diverse ecosystems and natural marvels, and supports a thriving hunting and outdoors culture that draws people from around the world.\\n\\n\"},{\"attributes\":{\"image\":\"http://www.1zoom.net/big2/913/256951-svetik.jpg\"},\"insert\":1},{\"insert\":\"\\n\"}]}"
Note.create(title: "Colorado", body: colorado_body, author_id: 1, notebook_id: 1)

utah_body = "{\"ops\":[{\"attributes\":{\"bold\":true,\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\",\"link\":\"http://www.utah.com/\"},\"insert\":\"Utah\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\", located in the \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\",\"link\":\"https://en.wikivoyage.org/wiki/Southwest_(United_States_of_America)\"},\"insert\":\"Southwest\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\" region of the \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\",\"link\":\"https://en.wikivoyage.org/wiki/United_States\"},\"insert\":\"United States\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\", is well known for its incredible scenic beauty and year round outdoor activities including skiing, snowboarding, hiking, boating, water skiing, horseback riding, camping, and rock climbing. The capital city of \"},{\"attributes\":{\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\",\"link\":\"https://en.wikivoyage.org/wiki/Salt_Lake_City\"},\"insert\":\"Salt Lake City\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\" has a number of unique modern and historical sites to visit, including Temple Square, the headquarters for the Mormon church.\"},{\"insert\":\"\\n\\n\"},{\"attributes\":{\"image\":\"http://www.jimshoemakerphotography.com/data/photos/12_1arches50.jpg\"},\"insert\":1},{\"insert\":\"\\n\"}]}"
Note.create(title: "Utah", body: utah_body, author_id: 1, notebook_id: 1)

Notebook.create(title: "New England", description: '{"ops":[{"insert":"States in New England."}]}', author_id: 1)

vermont_body = "{\"ops\":[{\"attributes\":{\"bold\":true,\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\",\"link\":\"http://www.vermontvacation.com/\"},\"insert\":\"Vermont\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\" is in the \"},{\"attributes\":{\"link\":\"https://en.wikivoyage.org/wiki/New_England\",\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"New England\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\" region of the \"},{\"attributes\":{\"link\":\"https://en.wikivoyage.org/wiki/United_States\",\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"United States\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\". The Green Mountain State is known for its beautiful fall foliage and its maple syrup. It is a popular destination for hiking and skiing.\"},{\"insert\":\"\\n\\n\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"Vermont is the second smallest state in terms of population (it has 626,431 residents) and the sixth smallest in geographic area. Lake Champlain, the nation's sixth-largest freshwater body lies at the northwest border with \"},{\"attributes\":{\"link\":\"https://en.wikivoyage.org/wiki/New_York_(state)\",\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"New York State\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\" and \"},{\"attributes\":{\"link\":\"https://en.wikivoyage.org/wiki/Canada\",\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"Canada\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\". The state is extremely rural, its valleys littered with farms. Its largest city is Burlington, pop. 42,417. Among the state's major exports are cheese, maple syrup, marble, slate, and granite.\"},{\"insert\":\"\\n\\n\"},{\"attributes\":{\"image\":\"http://blypix.com/Art/Wallpaper/images/new_england_fall_2009_3862_wallpaper.jpg\"},\"insert\":1},{\"insert\":\"\\n\"}]}"
Note.create(title: "Vermont", body: vermont_body, author_id: 1, notebook_id: 2)

maine_body = "{\"ops\":[{\"attributes\":{\"link\":\"http://www.visitmaine.com/\",\"bold\":true,\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"Maine\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\" is the easternmost state in \"},{\"attributes\":{\"link\":\"https://en.wikivoyage.org/wiki/New_England\",\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"New England\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\". Its rugged, indented coastline and glacier-carved, forested interior give this state its unique character and have shaped the character of its people.\"},{\"insert\":\"\\n\\n\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"Maine is a northeastern state, but one of the most sparsely populated states in the \"},{\"attributes\":{\"link\":\"https://en.wikivoyage.org/wiki/USA\",\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"USA\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\". Its northern reaches, known as The Great North Woods, are largely pristine wilderness. The coastal regions, supported over the years by fishing, lobstering and tourism, are more heavily populated, particularly in the southern, more temperate part of the state. Although the water is decidedly cool, Maine's mostly rocky coastline and more than 60 lighthouses make for some beautiful scenery. That, a comfortable place to stay, and a Maine lobster may be all you need.\"},{\"insert\":\"\\n\\n\"},{\"attributes\":{\"image\":\"http://s1.1zoom.me/big3/154/353203-admin.jpg\"},\"insert\":1},{\"insert\":\"\\n\"}]}"
Note.create(title: "Maine", body: maine_body, author_id: 1, notebook_id: 2)

new_hampshire_body = "{\"ops\":[{\"attributes\":{\"link\":\"http://www.visitnh.gov/\",\"bold\":true,\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"New Hampshire\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\" is a state in \"},{\"attributes\":{\"link\":\"https://en.wikivoyage.org/wiki/New_England\",\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"New England\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\" in the north east of the \"},{\"attributes\":{\"link\":\"https://en.wikivoyage.org/wiki/United_States_of_America\",\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"United States of America\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\". Noted for its terse and independent inhabitants and cold winters, New Hampshire has much natural beauty.\"},{\"insert\":\"\\n\\n\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"Residents of the state are proud of the nature around them, so careless actions that damage the local environment are not appreciated. If hiking in the White Mountains, make certain that your travel plans are sound, as volunteer rescue teams do not appreciate being called in the middle of the night to find lost tourists. However, as tourism is the main industry in New Hampshire, tourists are certainly greatly appreciated.\"},{\"insert\":\"\\n\\n\"},{\"attributes\":{\"image\":\"https://drscdn.500px.org/photo/4566588/m%3D2048/30c44b0fdf2419bc34f3c0fbd1456ae6\"},\"insert\":1},{\"insert\":\"\\n\"}]}"
Note.create(title: "New Hampshire", body: new_hampshire_body, author_id: 1, notebook_id: 2)

rhode_island_body = "{\"ops\":[{\"attributes\":{\"bold\":true,\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\",\"link\":\"http://www.visitrhodeisland.com/\"},\"insert\":\"Rhode Island\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\" is the smallest state in the \"},{\"attributes\":{\"link\":\"https://en.wikivoyage.org/wiki/United_States_of_America\",\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"United States of America\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\", tucked between \"},{\"attributes\":{\"link\":\"https://en.wikivoyage.org/wiki/Massachusetts\",\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"Massachusetts\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\" and \"},{\"attributes\":{\"link\":\"https://en.wikivoyage.org/wiki/Connecticut\",\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"Connecticut\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\" in \"},{\"attributes\":{\"link\":\"https://en.wikivoyage.org/wiki/New_England\",\"color\":\"rgb(11, 0, 128)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\"New England\"},{\"attributes\":{\"color\":\"rgb(37, 37, 37)\",\"font\":\"sans-serif\",\"size\":\"14px\"},\"insert\":\". Nonetheless, it has over 400 miles of coastline, courtesy of Narragansett Bay and islands such as Aquidneck Island, home to Newport, the \\\"City by the Sea.\\\"\"},{\"insert\":\"\\n\\n\"},{\"attributes\":{\"image\":\"http://www.micbla56.dreamhosters.com/blog/wp-content/uploads/2014/12/MAB_20140623_RI_BLOCK_ISLAND_NORTH_LIGHT_SUNSET_8000973.jpg\"},\"insert\":1},{\"insert\":\"\\n\"}]}"
Note.create(title: "Rhode Island", body: rhode_island_body, author_id: 1, notebook_id: 2)

wyoming_note = Note.all[0]
wyoming_note.tags.create(name: "wyoming")
wyoming_note.tags.create(name: "barn")
wyoming_note.tags.create(name: "mountains")

nevada_note = Note.all[1]
nevada_note.tags.create(name: "nevada")
nevada_note.tags.create(name: "road")
nevada_note.tags.create(name: "sky")

colorado_note = Note.all[2]
colorado_note.tags.create(name: "colorado")
colorado_note.tags.create(name: "mountains")
colorado_note.tags.create(name: "skiing")

utah_note = Note.all[3]
utah_note.tags.create(name: "utah")
utah_note.tags.create(name: "desert")
utah_note.tags.create(name: "clouds")

vermont_note = Note.all[4]
vermont_note.tags.create(name: "vermont")
vermont_note.tags.create(name: "lakes")
vermont_note.tags.create(name: "maplesyrup")

maine_note = Note.all[5]
maine_note.tags.create(name: "maine")
maine_note.tags.create(name: "lighthouses")
maine_note.tags.create(name: "ocean")

new_hampshire_note = Note.all[6]
new_hampshire_note.tags.create(name: "newhampshire")
new_hampshire_note.tags.create(name: "whitemountains")
new_hampshire_note.tags.create(name: "trees")

rhode_island_note = Note.all[7]
rhode_island_note.tags.create(name: "rhodeisland")
rhode_island_note.tags.create(name: "beach")
rhode_island_note.tags.create(name: "lighthouses")
